server:
  port: 3333
 
spring:
  application:
    name: secondmemberapplication
  boot:
    admin:
     client:
      url:
      - http://localhost:1111
  
eureka:
  client:
    service-url:
      DefaultZone:
        http://localhost:8761/eureka/