spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: first
          predicates:
            - Path=/first/**
          uri: lb://FIRSTMEMBERAPPLICATION                #localhost:8081
        - id: second
          predicates:
            - Path=/second/**
          uri: lb://SECONDMEMBERAPPLICATION                #localhost:8088
